project_name: iseven-gen
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: iseven-gen
    ldflags:
      - -s -w
      - -X github.com/kmdkuk/iseven-gen/version.Version={{.Version}}
      - -X github.com/kmdkuk/iseven-gen/version.Revision={{.ShortCommit}}
      - -X github.com/kmdkuk/iseven-gen/version.BuildDate={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: binary
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: checksums.txt
release:
  prerelease: auto
